version: '2'
services:
    elasticsearch:
        image: elasticsearch:2.2.1
    kibana:
        image: kibana:4.4.2
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
            - elasticsearch
    logstash:
        image: logstash:2.2.2
        command: "-f /app/logstash.conf --verbose"
        volumes:
            - ./logstash/:/app/
        ports:
            - "5555:5555"
        depends_on:
            - elasticsearch
